# Generated by Django 4.2.4 on 2023-09-27 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='verify_code',
            field=models.CharField(default=1, max_length=50, verbose_name='Верификация'),
            preserve_default=False,
        ),
    ]
