# Generated by Django 4.2.4 on 2023-09-21 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_version'),
    ]

    operations = [
        migrations.RenameField(
            model_name='version',
            old_name='version_indicator',
            new_name='is_active',
        ),
    ]
